### ISSUE TITLE
Implement parsing of union decls

### ISSUE THREAD

**Issue by rightfold** [mill-lang/millc#16]
So @vendethiel I had the following in mind for sum types:

    union Option[T] { // (not implementing generics just yet; just for illustrative purposes)
        Some(value: T)
        None
    }
    
    union Lexeme {
        common(location: Int) // common fields are prepended to all data constructors' parameter lists
        Identifier(name: String) // actually Identifier(location: Int, name: String)
        Class // actually Class(location: Int)
    }

**Comment by rightfold** [comment]
Hello world doesn't need `common`, though.

**Comment by vendethiel** [comment]
I don't really like the looks of `common`

**Comment by rightfold** [comment]
union Lexeme {
        location: Int // common fields are prepended to all data constructors' parameter lists
        Identifier(name: String) // actually Identifier(location: Int, name: String)
        Class // actually Class(location: Int)
    }

how'bout that?

**Comment by vendethiel** [comment]
yes, I was thinking about that, but then... is there enough visual separation? :v

**Comment by rightfold** [comment]
ok. this issue excludes common fields.
