### ISSUE TITLE
Implement parsing of struct literals

### ISSUE THREAD

**Issue by rightfold** [mill-lang/millc#17]
Given:

    struct User { id: Int name: String }

You can construct it as follows:

    let user = User{id: 1, name: "rightfold"}

Questions:

1. Should we allow `User{name: "rightfold", id: 1}`? I.e. different order.
2. Should we allow `User{1, "rightfold"}`? (In same order, of course.)

**Comment by vendethiel** [comment]
I vote 1) ok (maybe a style warning...) 2) no

**Comment by rightfold** [comment]
I agree with 2. Let's leave 1 open for now.
