### ISSUE TITLE
Add many more codegen test cases and figure out a better way to test it.

### ISSUE THREAD

**Issue by rightfold** [mill-lang/millc#38]

**Comment by vendethiel** [comment]
Monkey testing? Generating random AST / fuzzying

**Comment by rightfold** [comment]
How are you going to test codegen of a random AST?

**Comment by rightfold** [comment]
Do you want to test whether codegen works at all for all well-typed ASTs?

**Comment by vendethiel** [comment]
yes

**Comment by vendethiel** [comment]
and that the VM doesn't crash running those ASTs, probably

**Comment by vendethiel** [comment]
like https://github.com/estools/esfuzz

**Comment by rightfold** [comment]
Shiny.
